### ISSUE TITLE
Client - Values of to be edited user are not updated

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless-graphql#12]
Steps to reproduce:
- Go to the users table
- Click on `edit` in the table
- Go Back to the users table (wit the browsers back button)
- Select another user

You'll see the value of the old user.

This has smth. to do with the fact that the state is updated after the component is mounted. We could use [Redux form](https://github.com/erikras/redux-form) but I don't want to introduce another dependency for such as simple problem.

**Comment by nikgraf** [comment]
@brettstack since we reimplemented the whole project I will close this. Let us know if you have any questions regarding the new version
