### ISSUE TITLE
Format variables to camel case instead of snake case

### ISSUE THREAD

**Issue by iamclaytonray** [serverless/serverless-graphql#157]
It's not very conventional to throw `snake_case` in JavaScript. The preferred/conventional method is `camelCase`. This casing style can be found in places like <a href="https://github.com/serverless/serverless-graphql-apollo/blob/master/app-backend/schema.js">the GQL Schema</a> and the <a href="https://github.com/serverless/serverless-graphql-apollo/blob/master/app-client/src/components/User.js">User component.</a> Of course, there are other areas but I propose changing it. I'll send a PR your way if you'll take it.

**Comment by sid88in** [comment]
@nikgraf any thoughts on this?
