### ISSUE TITLE
Add AWS AppSync Integrations

### ISSUE THREAD

**Issue by jthegedus** [serverless/serverless-graphql#195]
AWS just announced their own serverless GraphQL service which provisions DynamoDB from the schema and Lambda for custom resolvers as well as support for subscriptions (but completely managed so also serverless-ly). - see https://aws.amazon.com/blogs/aws/introducing-amazon-appsync/

Their client SDK - https://github.com/awslabs/aws-mobile-appsync-sdk-js - is also built on Apollo with apollo-link being the main mechanism to support offline, s3 objects and subscriptions.

What are your thoughts on making this the new stack for this starter kit?

**Comment by sid88in** [comment]
Right on! 👍 

AWS has scheduled 2 sessions today on GraphQL in re-invent and I am actually outside the conference hall waiting to get in :D Excited to see what they are doing and how we can combine it in our current stack !!

**Comment by sid88in** [comment]
@jthegedus here it is - https://github.com/serverless/serverless-graphql-apollo/pull/196 :) merged now. feel free to play with it and give feedback

**Comment by sid88in** [comment]
@jthegedus they are merged now :) Please let me know if you have any feedback/questions. Would love more contributions so feel free to fix minor issues in open PR's if you have some time.

**Comment by jthegedus** [comment]
If I find anything and can contribute a solution, I will! :smile:

**Comment by maziarz** [comment]
I will be actively working on a deploy tool for AppSync. Is there any activity in this context at the moment?

**Comment by imolorhe** [comment]
@harleyguru You can test appsync GraphQL subscriptions in [Altair](https://altair.sirmuel.design/).
