### ISSUE TITLE
405 Method not allowed on production deployment

### ISSUE THREAD

**Issue by fodurrr** [serverless/serverless-graphql#274]
Hi,

I am struggling with the production deployment to get it work however local development working fine.

When I deploy frontend to AWS S3 then I get an error on the frontend that 405 Method not allowed from GraphQL endpoint.

I tried everything already but I just cannot find out the reason.

This is what I use in the security.env.prod :

REACT_APP_HANDLE=peterfodor-me --> this is the profile name I use as AWS credentials
REACT_APP_CONSUMER_KEY=  {my AWS access key, belongs to the profile above}
REACT_APP_SECRET_KEY= {my AWS secret key, belongs to the profile above}

What are these 3 variables exactly, from where they are coming? Did I make it right above?
REACT_APP_HANDLE= ???
REACT_APP_CONSUMER_KEY= ???
REACT_APP_SECRET_KEY= ???

I still suspect that something wrong with these variables but I am not sure.

![image](https://user-images.githubusercontent.com/10008597/35360547-fb620ff2-0155-11e8-854a-a0821b5fb901.png)

![image](https://user-images.githubusercontent.com/10008597/35360771-cc4cca80-0156-11e8-99be-c7efd8f23b52.png)

Please can somebody help me??

**Comment by sid88in** [comment]
@fodurrr which backend integration are you using? RDS/Dynamo or Rest API?

REACT_APP_HANDLE= ???
REACT_APP_CONSUMER_KEY= ???
REACT_APP_SECRET_KEY= ???

They come from config files and are set in the apollo client. Handle is the user twitter handle in our examples. for instance - for me its sidg_sid or if you generate test data and insert it in prod you will have to check the test data handle for instance LeoDiCaprio.

Consumer key and Secret are not required for dynamo or RDS integrations but is required for you to query via REST API (twitter integration). It has nothing to do with AWS keys!

We will try to explain it better in readme
thanks
Sid

**Comment by fodurrr** [comment]
I am using just dynamodb.... I though that it is not needed but I tried everything :)
What I also do not understand why in the readme the s3 deployments are using https, for me S3 deployment works just with Http, may be therefore I have the other error in chrome console that only secure connection are allowed for serviceworkers.

I am still puzzled. may be this http instead of https is the reason but I do not understand how you get from the boilerplate https S3 site.

**Comment by fodurrr** [comment]
thanks for your quick answer @sid88in , unfortunately I used the original config files as you proposed and I still have the same issue like you can see the new screenshots.

![image](https://user-images.githubusercontent.com/10008597/35408449-067118aa-0207-11e8-9041-d3d2e080cc33.png)

![image](https://user-images.githubusercontent.com/10008597/35408487-33743800-0207-11e8-9198-4aace217d2b1.png)

Would you be so kind to check what do I do wrong? Because I have an other serverless project with Graphql/Apollo/Dynamodb similar to this one and it has the same issue. Works fine locally but when it is deployed to amazon aws then the qraphql query refused by aws.

Here is the git repo if  anybody could help me would be nice.

[https://github.com/fodurrr/sls-graphql-master](https://github.com/fodurrr/sls-graphql-master)

**Comment by sid88in** [comment]
@fodurrr these integrations were tested before merging in this repo but maybe some breaking change went it. I'll give it a shot and maybe we can skype and debug together later today.

How about you DM me @sidg_sid

**Comment by fodurrr** [comment]
Sorry @sidg_sid what you mean by "DM me @sidg_sid" ?
I would be more then happy if you could help me out. My skype address is: fodurrr

**Comment by sid88in** [comment]
;) I mean reach out to me on twitter :D you can add me on skype: sid88in

**Comment by fodurrr** [comment]
Thanks for your kindness, I solved the issue it was really my bad :((((
I put the graphql endpoint in quotes in the security.env.prod file.

I was suffering with this for soo long. But you motivated me :) I over-complicated the issue for my self....

OMG :)

Nevertheless may be later I will add you on skype If you dont mind because I plan to work with serverless more and more.

Thanks again

**Comment by sid88in** [comment]
YAYYY! HI 5! :)

Also, feel free to contribute to the repo ;) 
cheers
Sid

**Comment by jordo1138** [comment]
I did the same thing just now @fodurrr lol first took out the <> and then the "" and it's fine now in prod
the config by default shows 
REACT_APP_GRAPHQL_ENDPOINT="<your custom API endpoint e.g. https://XXXXXXXXXX.execute-api.us-east-1.amazonaws.com/production/graphql>"

you need to remove the "< >" in order for it to not give you the 405 error in prod
