### ISSUE TITLE
Server-Side Caching

### ISSUE THREAD

**Issue by ac360** [serverless/serverless-graphql#30]
We'd like to offer easy server-side caching, but we can't do that right now with a single endpoint containing only a POST request to API Gateway. 

We should create a second Endpoint on the existing `data` Lambda which features a GET method.  The GraphQL request should be provided in a query string, which API Gateway needs for caching.

Not sure what type of challenges we'll run into implementing this, but if this works, great!

@kevinold @pmuens @breandr Do you see any potential issues with this?

**Comment by breandr** [comment]
So there are two levels of cache - client (browser) and server (API
Gateway). By default, this boilerplate should only leverage the client
cache, as API Gateway charges additional fees for caching. We should
mention this and point them at the API Gateway caching docs.

It might be a good idea to configure caching for the query string parameter
so that enabling caching is as easy as turning it on at the stage.

**Comment by ac360** [comment]
@breandr Yes, making it easy for people so all they have to do is turn caching on in a particular stage is the goal.  

I believe this will require creating an additional GET endpoint, with the cache settings set to a stage variable, which can be true or false, and adding the GET request logic to the client-side.

**Comment by breandr** [comment]
I think it's more a matter of setting up the GET method with a "query"
query string parameter on the method request and adding
"method.input.params.query" to the list of cache key parameters. Adding
cache at this level will have no effect (or additional fee) until you
enable cache on the stage. Then, as we do with POST, pass "query" through
in the request template.

**Comment by breandr** [comment]
How do I add a request parameter for the sole purpose of using it in the request template? The docs only mention this way to define request parameters:

```json
"requestParameters": {
  "integration.request.querystring.query": "method.request.querystring.query"
}
```

My understanding is this will set up both a method and integration request parameter, however we do not need the latter for this purpose.

I also had to dig into the source to find out how to add cache key parameters - this should be added to the serverless docs.

**Comment by breandr** [comment]
README update to follow later - do you think it should be in the FAQ or somewhere else?

**Comment by ac360** [comment]
@breandr Fantastic work!  I think we should get this in the README.  It's a valuable feature and people should be aware of it.

**Comment by pmuens** [comment]
Great addition. A GET endpoint is also important for stuff such as "activate your account" or other stuff where the user clicks on a link.

**Comment by ac360** [comment]
@pmuens How should this work on the client-side?

**Comment by pmuens** [comment]
We've implemented it this way:

```
// s-function.json
  ...
    {
      "path": "graphql",
      "method": "GET",
      "type": "AWS",
      "authorizationType": "none",
      "authorizerFunction": false,
      "customAuthorizer": false,
      "apiKeyRequired": false,
      "requestParameters": {},
      "requestTemplates": {
        "application/json": "{\"query\" : $input.params(\"query\")}"
      },
      "responses": {
        "400": {
          "statusCode": "400"
        },
        "default": {
          "statusCode": "200",
          "responseParameters": {},
          "responseModels": {},
          "responseTemplates": {
            "application/json": ""
          }
        }
      }
    }
  ...
```

```
// The link with the GraphQL mutation
...

let confirmSubscriptionLink = `http://example.com/endpoint?query=` encodeURIComponent(JSON.stringify(`mutation confirmSubscription{subscriber:confirmSubscription(id:"${subscriberId}"){id,email}}`));
```

**Comment by breandr** [comment]
Updated README but couldn't find anything in serverless docs regarding enabling caching on a stage, so for now it's just pointing users to the API Gateway Caching docs.

**Comment by HyperBrain** [comment]
@breandr FYI, I created https://github.com/serverless/serverless/issues/1021 a time ago for the documentation of APIG caching.
