### ISSUE TITLE
Updating AppSync endpoint rather than creating new one?

### ISSUE THREAD

**Issue by lolcoolkat** [serverless/serverless-graphql#309]
When I deploy the AppSync backend via node deploy-dynamodb.js i'd like it to update an existing appsync deployment.. rather than creating a new one. Is this possible.. if so can someone please share? :)

**Comment by sid88in** [comment]
@lolcoolkat you have two options:

1. add update sdk's in [deploy script](https://github.com/serverless/serverless-graphql/blob/master/app-backend/appsync/dynamo-elasticsearch/deploy-elasticsearch.js)

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/AppSync.html#updateGraphqlApi-property

2. add integration in https://github.com/sid88in/serverless-appsync-plugin/pulls

**Comment by lolcoolkat** [comment]
Thank you @sid88in !!!!
