### ISSUE TITLE
Error transforming the velocity template

### ISSUE THREAD

**Issue by lolcoolkat** [serverless/serverless-graphql#311]
Getting this error ... after I deployed and setup everything.. using AppSync client!

`GraphQL error: java.util.concurrent.ExecutionException: com.amazonaws.deepdish.transform.velocity.TransformationRenderingException: Error transforming the velocity template`

![Error](https://image.prntscr.com/image/UvrL2O5-S3GCFBcjh9sgoA.png)

The query that's causing the error is **Query.meInfo**

![Error](https://image.prntscr.com/image/3cD-EpfaS5uCsFu58a1fQg.png)

Any ideas? :)

**Comment by sid88in** [comment]
something is not right, can you please check if your GraphQL endpoint is working in postman.

**Comment by lolcoolkat** [comment]
@sid88in I can access the url if thats what you're referring to, yes.

**Comment by iuriikozuliak** [comment]
@lolcoolkat got the same error on my initial setup, fixed by adding a user to the Users table with the same handle as cognito username.

**Comment by sid88in** [comment]
@iuriikozuliak thanks for pointing this out. Yes, because meInfo derives value from cognito user base, the same username must be present in the fake dataset.

Can you please create a PR and update that in the readme ;)

**Comment by lolcoolkat** [comment]
@iuriikozuliak @sid88in yep figured out I needed to add my handle to the user table.. after like 2 hours of debugging hehe :D

**Comment by sid88in** [comment]
meowww! @lolcoolkat
