### ISSUE TITLE
ConcurrentModificationException: Schema is currently being altered, please wait until that is complete

### ISSUE THREAD

**Issue by lolcoolkat** [serverless/serverless-graphql#316]
Keep receiving this error.. when updating the resolvers and the process crashes.

`ConcurrentModificationException: Schema is currently being altered, please wait until that is complete.`

![Error](https://image.prntscr.com/image/32snWo8FSUOG5JNzDi-TLQ.png)

Any ideas? :)

**Comment by sid88in** [comment]
@lolcoolkat are you using appsync plugin or deploy script in this repo?
I have seen this error before when your types are not set properly in the deploy script.

**Comment by lolcoolkat** [comment]
@sid88in i'm assuming you're talking about the types in my schema? If so, I don't have any custom types in my schema file.. just what was there by default.

And yes I am using the deploy script :)
