### ISSUE TITLE
Rename `back` to `backend`?

### ISSUE THREAD

**Issue by nikgraf** [serverless/serverless-graphql#32]
I was reading through the readme to run through the setup. The name `back` initially was confusing. What do you think about renaming it to `backend`?

**Comment by breandr** [comment]
I feel like we need to be consistent: either front-end and back-end or
client and server. I understand the desire to not name it "server", but
developers using serverless understand that there is still a server.

**Comment by nikgraf** [comment]
Hehe, yeah I had similar thoughts about server. `backend` & `frontend` sounds good to me … I suggest to leave out the hyphen. Both versions seem to be valid according to Google & Wiktionary

**Comment by ac360** [comment]
There is a high likelihood we will be including other clients in our boilerplates (Alexa, IoT devices, etc.).  We're waiting on a plugin from @jerwallace which adds IoT support to the framework.  So `frontend` might not be appropriate.  `backend` sounds fine.

**Comment by ryansb** [comment]
Ugh, three more letters!?!?!

Kidding. :+1: for backend, but for the web client maybe the right name would be `website` or `webclient`? That way it'd be obvious that it's the web client, as opposed to a mobile client (or client library, or ...).

**Comment by pmuens** [comment]
+1 for web client as a mobile client might follow as well (with ReactNative)!

**Comment by darthtrevino** [comment]
How feasible would it be to flatten the directory structure? The top level client and back folders seem useless

    client
    └─── src
         └─── package.json
              <project files>
    back
    └─── api
         └─── package.json
               <project files>
    └─── events

==> 

    client
    └─── package.json
         <project files>
    back
    └─── package.json
         <project files>
    └─── events

**Comment by nikgraf** [comment]
Resolved with the new structure. In case you have concerns about the new structure, please let me know.
