### ISSUE TITLE
Is not possible not to use cognito ?

### ISSUE THREAD

**Issue by jeremyputeaux** [serverless/serverless-graphql#337]
Hello,

Everything is in the title.

I need to make accounts without password.
People will set their password when they confirm their email.
I don't think I can do this with cogito. I can't find the information anywhere.
Thank you.

**Comment by sid88in** [comment]
Hey @jeremyputeaux - not sure if I understand your question. Looks like you don't want to authenticate your API via cognito. OK, thats perfectly fine. We have two backend integrations - 1) api gateway + lambda where you are free to not authenticate api or use api key or custom authentication if you want.  2) appsync - you have to authenticate api in this case via api key or cognito or custom auth.

**Comment by jeremyputeaux** [comment]
OK thanks a lot

**Comment by fgiarritiello** [comment]
@sid88in Do you have an example of how to use appsync with custom auth.
In my specific case I'm using auth0 to get a jwt and use it to authorize access to the microservice rest apis. I'm now trying to wrap the rest apis with appsync and would like to use the same jwt to authenticate the graphql api. Any idea how to achieve this?

Thanks
