### ISSUE TITLE
update-appsync does not work with API_KEY settings

### ISSUE THREAD

**Issue by eltonio450** [serverless/serverless-graphql#343]
Creating the appsync app with the API_KEY flag worked:

![image](https://user-images.githubusercontent.com/6675365/37612505-af23fbc6-2ba5-11e8-8bde-7d02a5a6db90.png)

but updating it through update-appsync did not:

![image](https://user-images.githubusercontent.com/6675365/37612555-ca6ece1a-2ba5-11e8-9024-8d618e7f8180.png)
![image](https://user-images.githubusercontent.com/6675365/37612565-d664d1b0-2ba5-11e8-9597-ed75da4e47bb.png)

Workaround: activate a random userPoolConfig
![image](https://user-images.githubusercontent.com/6675365/37612594-f15f24ca-2ba5-11e8-9f37-c8a299c37117.png)

I am not sure of why, but I imagine that there is still a check of Cognito User Pool for update-appsync, which has been removed of deploy-appsync since sid88in/serverless-appsync-plugin#51

**Comment by sid88in** [comment]
@eltonio450 can you please check if you are using latest npm version 0.0.6. Version 0.0.5 doesn't have update api key functionality but 0.0.6 should work. Let me know and I can test again. thanks!

**Comment by eltonio450** [comment]
@sid88in my bad, I thought I had the last version but was reading the wrong package.json file :(

**Comment by sid88in** [comment]
glad you made it work ! 👍
