### ISSUE TITLE
Lambda:IllegalArgument

### ISSUE THREAD

**Issue by merunga** [serverless/serverless-graphql#346]
I don't know if this is an issue with the examples themselves or with [serverless-appsync-plugin](https://github.com/sid88in/serverless-appsync-plugin).

But, after deploying [appsync api with lamba datasource](https://github.com/serverless/serverless-graphql/tree/master/app-backend/appsync/lambda) and trying to connect with [appsync-web-client](https://github.com/serverless/serverless-graphql/tree/master/app-client/appsync-client)

Every request to the appsync api ends up with the following error:
```
{
  "data": null,
  "errors": [{
    "path": ["meInfo"],
    "errorType": "Lambda:IllegalArgument",
    "locations": [{
      "line": 2,
      "column": 3
    }],
    "message": "java.lang.IllegalArgumentException: Illegal ARN format detected, the relative-id must follow the format function:<name>:<alias>"
  }]
}
```

![image](https://user-images.githubusercontent.com/211721/38121247-c016555a-3393-11e8-90dd-75b6c07eb31b.png)

Also tried setting up a serverless version of events schema template that comes by default with appsync, same result

**Comment by sid88in** [comment]
@merunga looks like some settings are not correct. 

1. Please double check the resource ARN's used while creating the backend API. You can double check if your API is infact working by going into AppSync console.

2. Please double check the input configs for the client are set properly with correct API name.

**Comment by merunga** [comment]
Hi @sid88in thanks for the quick reply.
I've have already checked the two places where ARNs are used:
- the appsync dataSource
- the role policy resources

Is there some other place where I should check?  What do you mean with ***the input configs for the client***?

Just to be clear, I have not changed anything in the serverless.yml file except for `custom.accountId` and `custom.userPoolConfig.userPoolId'. All the other is exactly as it's defined in the repo. Shouldn't this work by default?

I'll keep looking

**Comment by sid88in** [comment]
@merunga I would first make sure AppSync API's are created with correct input ARN's for AWS Lambda. You can try that by either 1) making an API call directly from GraphiQL in AppSync Console or 2) invoking lambda with a test event on lambda console. Now, if you get an error then there is something not right with your backend setup. 

Now, if the above step completes successfully, then you should check config/security.env because when you kickstart the client it takes some config params as an input (you can check package json for yarn start command). Please make sure your GraphQL endpoint is configured there.

**Comment by merunga** [comment]
@sid88in graphiql in appsync console is returning the same error. I'll check it out. Thanks for your support!

Hope to come back with an explanation!

**Comment by sid88in** [comment]
@merunga sounds good. The problem seems to be with the backend API creation. Please check the AWS lambda resource ARN.

**Comment by kirkness** [comment]
Hello! I think it might be on this line https://github.com/serverless/serverless-graphql/blob/master/app-backend/appsync/lambda/serverless.yml#L61

`arn:aws:lambda:us-east-1:${self:custom.accountId}:serverless-graphql-appsync-lda-production-graphql`

Should become...

`arn:aws:lambda:us-east-1:${self:custom.accountId}:function:serverless-graphql-appsync-lda-production-graphql`
