### ISSUE TITLE
Unable to connect client to appsync api.

### ISSUE THREAD

**Issue by cbaron** [serverless/serverless-graphql#351]
Hello,

I was easily able to spin up an appsync graphql api using the `app-backend/appsync/dynamo` configuration.  Thank you!

However, its not clear that a service role is created.  Is that supposed to happen?

Also, I was able to spin up a client from `app-client/appsync-client`, but after user pool authentication,  I am left with the following error when attempting to retrieve information from graphql:

```
GraphQL error: Unable to assume role 
```

Please advise.

**Comment by dbackeus** [comment]
@cbaron did you find a solution? I'm struggling with this currently.

**Comment by cbaron** [comment]
I did!

The README does not include how to create the data sources and roles.   Check `app-backend/appsync/dynamo/package.json`'s scripts attribute to find the `deploy-prod` command.

**Comment by dbackeus** [comment]
I also solved this. What I did was:
- Realize that `serverless deploy-appsync` doesn't actually create roles / policies
- Run `serverless deploy` to have the roles / policie created
- Realize that there were some policy strings hardcoded to the us-east region while I'm using eu-west so manualla fixed them as well
