### ISSUE TITLE
AppSync & RDS

### ISSUE THREAD

**Issue by romainquellec** [serverless/serverless-graphql#355]
Hello.

Just wondering : Is it possible right now to use AppSync with a RDS database ?
(If I'm connecting my lambda to my database in RDS, everything should be fine ?)

Thanks !

**Comment by romainquellec** [comment]
(You can add the "Question" label)

**Comment by getsbydev** [comment]
Yes you can easily connect your AppSync service with a lambda function to access your amazon RDS database.
I'm using a node.js lambda-function and access my RDS database via knex.js

**Comment by sid88in** [comment]
+1 @getsbydev

**Comment by josoroma** [comment]
@getsbydev Would be awesome to see a simple functional code example of `AppSync + Lambda + RDS Postgres`. 

Thanks!
