### ISSUE TITLE
Region AppSync <> DynamoDB

### ISSUE THREAD

**Issue by romainquellec** [serverless/serverless-graphql#356]
Is it possible to configurate two different locations : 
One for AppSync (eu-west-1) and another one for DynamoDB (eu-west-2) ?

If so, how ?

(My current config is here : https://github.com/CuistotduCoin/cuistot/blob/master/backend/serverless.yml)

**Comment by sid88in** [comment]
@romainquellec similar issue has been created in serverless appsync plugin (I think PR exists - can you please look at that?)
