### ISSUE TITLE
Migrate app-backend/rest-api to Apollo Server 2.0

### ISSUE THREAD

**Issue by amerani** [serverless/serverless-graphql#364]
Apollo framework has released Apollo Server 2.0 and the corresponding lambda package `apollo-server-lambda`. I have started creating my own boilerplate (https://github.com/amerani/graphql-serverless-boilerplate) using this repo as inspiration. Is there any interest to upgrade apollo server here? I'd be happy to contribute.

**Comment by sid88in** [comment]
@amerani that would be great. If you can update this issue with all the changes you have in mind then we can give it a review and then you can create a PR to make those changes? Does that sound good? :)

**Comment by sid88in** [comment]
@amerani this all sounds great! please go ahead. I would request you to create PR's making change in 1 backend at a time and doing full testing E2E. I don't want us to create a *huge* PR which is difficult to test and have potential issues. We need to be super careful that things don't break and work E2E (including UI, Backend).

Looking forward to your work!

**Comment by amerani** [comment]
Done https://github.com/serverless/serverless-graphql/pull/365 💪
