### ISSUE TITLE
HELP WANTED: Relay example

### ISSUE THREAD

**Issue by M1chaelTran** [serverless/serverless-graphql#51]
Would be great if there's an example of this using **Relay** instead of Redux.

It would make more sense to use Relay with GraphQL than Redux IMO.

**Comment by flomotlik** [comment]
We are planning to add more examples in the future including Relay, it will take a while though until we're ready to do that.

**Comment by rafanami** [comment]
Yeah, but to use relay, the server needs to handle the variables as well.

**Comment by tobias-sc** [comment]
@flomotlik Could you provide some indication when you could release an update graphql sample based on serverless 1.x?

Currently what would you recommend to use this repo as a base or rather use serverless rc 1.0 and integrate graphql ourself?

Thank you!

**Comment by flomotlik** [comment]
@tobias-sc at the moment we don't have a timeframe to update this, so the best way forward is to use rc1 and integrate graphql directly. We've used it in one of our projects and its pretty straight forward.

**Comment by nikgraf** [comment]
Hey @tobias-sc, @rafanami & @M1chaelTran, we just updated the repository and added the setup for a Relay client. We are going to announce it later today. Please let us know if you have some feedback for us.

**Comment by M1chaelTran** [comment]
That's wonderful news @nikgraf 👍 
Look forward to trying it out.

**Comment by nikgraf** [comment]
@M1chaelTran looking forward to your feedback 👍

**Comment by tobias-sc** [comment]
@nikgraf & team - thank you for the upgrade and release.
We decided to go with the old version 0.5.x + Redux earlier and do not consider Relay at this stage.
