### ISSUE TITLE
`sls project` does not work

### ISSUE THREAD

**Issue by ajcrites** [serverless/serverless-graphql#52]
To get started, the docs say to install the `serverless` package and then run

    sls project install serverless-graphql

I've also tried with `sls -m my-project-name project install serverless-graphql`

This yields:

    Serverless Error ---------------------------------------

     command "project" not found, Run "serverless help" for
     a list of all available commands.

**Comment by ChaosSmith** [comment]
A workaround for this is to revert to an older version of serverless, ```try npm install -g serverless@0.5.6```

**Comment by GreenAsJade** [comment]
Yes - specifically, "project" is no longer supported, so the docs here need some update!

  https://github.com/serverless/serverless/issues/1841

**Comment by tonyxiao** [comment]
Is there any plan to update this project to serverless 1.0?

**Comment by nikgraf** [comment]
@tonyxiao yes, very soon 🙃

**Comment by nikgraf** [comment]
@tonyxiao @ajcrites @ChaosSmith just merged in the setup to get started with serverless 1.0 + Relay. I'm curious what you guys think about this starter kit … ✨

**Comment by tonyxiao** [comment]
@nikgraf what happened to offline / local server support btw?

**Comment by nikgraf** [comment]
@tonyxiao yet, there is no offline plugin in serverless 1.0, that's why this setup uses a local dev server to achieve the same thing

**Comment by tonyxiao** [comment]
just checked with server-less offline project and it seems to be coming soon :) https://github.com/dherault/serverless-offline/issues/111
