### ISSUE TITLE
Recomended way to split graphql API in different microservices

### ISSUE THREAD

**Issue by CapChrisCap** [serverless/serverless-graphql#61]
Hello, 

I would like to split my graphql API in different microservices. With REST this is quite easy because every route has its own microservice/lambda function. When using GraphQL, I have only one route/microservice, which has to handle the routing. Is there a recommended possibility in AWS to replace the normal routing GraphQL lambda function with a cheaper alternative in AWS? 

For example: 
query users --> getUsers lambda function
mutation login --> signIn lambda function
...

When I want to outsource my code, then I have to pay the two times: the GraphQL and the service lambda function. All in one, I have the struggle of separating my code and having one single and flexible API. 

Thanks in advance.

**Comment by nikgraf** [comment]
You could create multiple GraphQL endpoint, but I wouldn't recommend it. Internally we actually have one Lambda to handle the GraphQL queries which in the resolve functions calls other Lambdas (which we structured as microservices). Yes, this is a bit more expensive and adds a small overhead in terms of performance, but we decided to go that route to increase developer productivity and have clear separation.

Doing everything in one handler will work as well, but then I recommend to think about how to structure you code early on.

**Comment by morgs32** [comment]
@nikgraf have an example? I'm wondering how you break out the query and ship it to another graphql server

**Comment by nikgraf** [comment]
@morgs32 sorry. Missed that. Unfortunately I don't have anything I can share with you 🙁

**Comment by sid88in** [comment]
@nikgraf @morgs32 for multiple graphql endpoints you might wana to look at : https://dev-blog.apollodata.com/graphql-schema-stitching-8af23354ac37

**Comment by nikgraf** [comment]
Totally!
