### ISSUE TITLE
Alternative Architectures

### ISSUE THREAD

**Issue by johncmckim** [serverless/serverless-graphql#64]
I have been trying out GraphQL with my own projects recently. It seems to me that there are two approaches to a GraphQL API:
1. Monolithic GraphQL handler
2. GraphQL Backend for Front End

This project takes the monolithic approach, which is probably best for a boilerplate. It's easier to manage but it does have downsides. Like any monolith, as this grows it will be harder to manage the GraphQL handler and all the data the service owns. It also potentially violates the Principal of Least Access by having one handler access a wide set of data.

For those reasons, I think a [Backend for Frontend](http://samnewman.io/patterns/architectural/bff/) approach might be better long term. This is a diagram from the presentation I gave recently 

<img width="843" alt="screen shot 2016-10-16 at 7 35 38 am" src="https://cloud.githubusercontent.com/assets/1297227/19413533/2f429c12-9373-11e6-88a7-c40c6529919c.png">

The idea is that the GraphQL API, User Service and Moisture Service can be three separate microservices. The advantages of this is that it adheres to the principal of least access and it increases cohesion and reduces coupling.

I don't think that this design should be used for the boilerplate. It's possibly too complex for people that just want to get started. But, it would be good to make people aware of this design so they understand their options.

What do you think?

**Comment by nikgraf** [comment]
@johncmckim spot on! We actually use this structure to follow the  Backend for Frontend approach. In face the frontend team members are responsible for the GraphQL layer. From database.js we trigger other Lambdas to fetch the data managed by the backend team members.

Why did you assume this follows the `Monolithic GraphQL handler` pattern? How would you structure it differently to make it more obvious?

**Comment by johncmckim** [comment]
@nikgraf Is there more than one lambda in the project? I can only see one lambda, `handler.graphql` in `api/serverless.yml`.

In `query.js` the `resolve` function does this `(_, _args, context) => db.getViewer({}, context),`. That looks like a database call to me.

I would structure it so that it had a frontend and two serverless services.

```
|_ app // frontend code
|_ api-service // Serverless GraphQL service
  |_ graphql 
|_ user-service // Serverless User service
  |_ database 
```

**Comment by nikgraf** [comment]
@johncmckim In our case we actually have different repositories for it, but I like your proposal!

**Comment by johncmckim** [comment]
@nikgraf do you mean you do this in a real project or in this project? I can't see where this project uses `lambdaInvoke`. In `database/getViewer.js` it just returns a fake object.

I would 100% have each service in it's own repo for a normal project. But for a boilerplate it needs to be in one repo.

**Comment by dreadjr** [comment]
@johncmckim In BFF approach, would each microservice just be a lambda function or another graphql endpoint (a lambda function that accepts a graphql query) not necessarily an api gateway endpoint?

@nikgraf Are you saying there is another repo with other functions for this boilerplate?

**Comment by johncmckim** [comment]
@dreadjr I don't think there is any strict rules about this. But I would just have my GraphQL BFF invoke lambda functions in another service. This provides encapsulation over the data being accessed and is less latency than going through API Gateway for internal services.

**Comment by andreimc** [comment]
@johncmckim I am quite interested in something like this do you have any examples?

Some questions:

* How do you split your services - how granular do you go ? eg. I have a bunch of services that require data from one another. Do you go minimal common denominator to show something useful to the user.

* What sort off contract to you enforce between graphql handler and each of the services is it another graphql query ?

* What are the biggest problems you encountered with this approach ?

**Comment by johncmckim** [comment]
@andreimc we're working through some of these as we go.

*1. How do we split services.*
There's no one answer for this. Determining domain boundaries is one of the difficulties when creating microservices. I look at the data anything that needs direct access to the same data should be in the same service. Though it's not that simple as some services call other services to retrieve little bits of data they need.

*2. Contracts*
Right now we don't have standard contracts for data or messages. Though we're working on some ideas for that in this project - https://github.com/ACloudGuru/serverless-transceiver

*3. Biggest problems*
We're still early days with this. It works well for us right now. Testing is one of the more difficult issues. But I think other approaches such as monolithic REST APIs have worse problems.

**Comment by sid88in** [comment]
@nikgraf @johncmckim this is great discussion. I think our restructuring follows this approach already now? We can create different microservices or lambdas (as shown in system architecture diagram in readme) and then implement a resolver to fetch data from these services. If thats correct maybe we can close this issue?

**Comment by nikgraf** [comment]
@johncmckim are you still using serverless-transceiver?

**Comment by nikgraf** [comment]
In general my opinion nowadays is to start simple and only fan out to microservices once the endpoint grows to big. Lambda microservices can cause long waiting times when cold-starts are involved.

@johncmckim what's your experience?
